---
- name: Development
  hosts: all
  tasks:
    - name: Update kernel
      become: yes
      apt:
        state: latest
        name: 'linux-image*'
        only_upgrade: yes
        update_cache: yes
      register: update_kernel_results

    - name: Reboot
      become: yes
      reboot:
        reboot_timeout: 600
      when: update_kernel_results.changed

    - name: Re-gather facts
      setup:

    - name: Install kernel headers
      become: yes
      apt:
        state: present
        name:
          - linux-headers-{{ ansible_kernel }}

    - name: Install development packages
      become: yes
      apt:
        state: present
        name:
          - autoconf
          - automake
          - bison
          - flex
          - gcc
          - git
          - libfuse-dev
          - libgc-dev
          - libkrb5-dev
          - libncurses5-dev
          - libperl-dev
          - libtool
          - make
          - swig
          - wget
